for reference: https://www.javatpoint.com/machine-learning-random-forest-algorithm

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [5]:
data=pd.read_csv("C:/Users/91799/Downloads/Social_Network_Ads.csv")
print(data.to_string())
# data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617

In [3]:
x=data.drop(['Gender','User ID','Purchased'],axis=1)
x.values

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [4]:
y=data['Purchased']
y.values

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=4)

In [9]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=3,random_state=10)
clf.fit(x_train,y_train)


RandomForestClassifier(n_estimators=3, random_state=10)

In [14]:
y_pred=clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
      dtype=int64)

In [16]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

0.9015151515151515


In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm


array([[84,  5],
       [ 8, 35]], dtype=int64)

# 2. next data set

In [23]:
data2=pd.read_csv('50_Startups.csv')
data2

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [31]:
data2.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [32]:
pd.get_dummies(data2['State'])

California  Florida  New York
0            0        0         1
1            1        0         0
2            0        1         0
3            0        0         1
4            0        1         0
5            0        0         1
6            1        0         0
7            0        1         0
8            0        0         1
9            1        0         0
10           0        1         0
11           1        0         0
12           0        1         0
13           1        0         0
14           0        1         0
15           0        0         1
16           1        0         0
17           0        0         1
18           0        1         0
19           0        0         1
20           1        0         0
21           0        0         1
22           0        1         0
23           0        1         0
24           0        0         1
25           1        0         0
26           0        1         0
27           0        0         1
28           0        1         0
29           0        0         1
30           0        1         0
31           0        0         1
32           1        0         0
33           0        1         0
34           1        0         0
35           0        0         1
36           0        1         0
37           1        0         0
38           0        0         1
39           1        0         0
40           1        0         0
41           0        1         0
42           1        0         0
43           0        0         1
44           1        0         0
45           0        0         1
46           0        1         0
47           1        0         0
48           0        0         1
49           1        0         0

In [33]:
x=pd.get_dummies(data2['State'],drop_first=True)
x

Florida  New York
0         0         1
1         0         0
2         1         0
3         0         1
4         1         0
5         0         1
6         0         0
7         1         0
8         0         1
9         0         0
10        1         0
11        0         0
12        1         0
13        0         0
14        1         0
15        0         1
16        0         0
17        0         1
18        1         0
19        0         1
20        0         0
21        0         1
22        1         0
23        1         0
24        0         1
25        0         0
26        1         0
27        0         1
28        1         0
29        0         1
30        1         0
31        0         1
32        0         0
33        1         0
34        0         0
35        0         1
36        1         0
37        0         0
38        0         1
39        0         0
40        0         0
41        1         0
42        0         0
43        0         1
44        0         0
45        0         1
46        1         0
47        0         0
48        0         1
49        0         0

In [35]:
df=pd.concat([data2,x],axis=1)
df

R&D Spend  Administration  Marketing Spend       State     Profit  \
0   165349.20       136897.80        471784.10    New York  192261.83   
1   162597.70       151377.59        443898.53  California  191792.06   
2   153441.51       101145.55        407934.54     Florida  191050.39   
3   144372.41       118671.85        383199.62    New York  182901.99   
4   142107.34        91391.77        366168.42     Florida  166187.94   
5   131876.90        99814.71        362861.36    New York  156991.12   
6   134615.46       147198.87        127716.82  California  156122.51   
7   130298.13       145530.06        323876.68     Florida  155752.60   
8   120542.52       148718.95        311613.29    New York  152211.77   
9   123334.88       108679.17        304981.62  California  149759.96   
10  101913.08       110594.11        229160.95     Florida  146121.95   
11  100671.96        91790.61        249744.55  California  144259.40   
12   93863.75       127320.38        249839.44     Florida  141585.52   
13   91992.39       135495.07        252664.93  California  134307.35   
14  119943.24       156547.42        256512.92     Florida  132602.65   
15  114523.61       122616.84        261776.23    New York  129917.04   
16   78013.11       121597.55        264346.06  California  126992.93   
17   94657.16       145077.58        282574.31    New York  125370.37   
18   91749.16       114175.79        294919.57     Florida  124266.90   
19   86419.70       153514.11             0.00    New York  122776.86   
20   76253.86       113867.30        298664.47  California  118474.03   
21   78389.47       153773.43        299737.29    New York  111313.02   
22   73994.56       122782.75        303319.26     Florida  110352.25   
23   67532.53       105751.03        304768.73     Florida  108733.99   
24   77044.01        99281.34        140574.81    New York  108552.04   
25   64664.71       139553.16        137962.62  California  107404.34   
26   75328.87       144135.98        134050.07     Florida  105733.54   
27   72107.60       127864.55        353183.81    New York  105008.31   
28   66051.52       182645.56        118148.20     Florida  103282.38   
29   65605.48       153032.06        107138.38    New York  101004.64   
30   61994.48       115641.28         91131.24     Florida   99937.59   
31   61136.38       152701.92         88218.23    New York   97483.56   
32   63408.86       129219.61         46085.25  California   97427.84   
33   55493.95       103057.49        214634.81     Florida   96778.92   
34   46426.07       157693.92        210797.67  California   96712.80   
35   46014.02        85047.44        205517.64    New York   96479.51   
36   28663.76       127056.21        201126.82     Florida   90708.19   
37   44069.95        51283.14        197029.42  California   89949.14   
38   20229.59        65947.93        185265.10    New York   81229.06   
39   38558.51        82982.09        174999.30  California   81005.76   
40   28754.33       118546.05        172795.67  California   78239.91   
41   27892.92        84710.77        164470.71     Florida   77798.83   
42   23640.93        96189.63        148001.11  California   71498.49   
43   15505.73       127382.30         35534.17    New York   69758.98   
44   22177.74       154806.14         28334.72  California   65200.33   
45    1000.23       124153.04          1903.93    New York   64926.08   
46    1315.46       115816.21        297114.46     Florida   49490.75   
47       0.00       135426.92             0.00  California   42559.73   
48     542.05        51743.15             0.00    New York   35673.41   
49       0.00       116983.80         45173.06  California   14681.40   

    Florida  New York  
0         0         1  
1         0         0  
2         1         0  
3         0         1  
4         1         0  
5         0         1  
6         0         0  
7         1         0  
8         0         1  
9         0         0  
10        1     

In [37]:
data_new=df.drop(['State'],axis=1)
data_new

R&D Spend  Administration  Marketing Spend     Profit  Florida  New York
0   165349.20       136897.80        471784.10  192261.83        0         1
1   162597.70       151377.59        443898.53  191792.06        0         0
2   153441.51       101145.55        407934.54  191050.39        1         0
3   144372.41       118671.85        383199.62  182901.99        0         1
4   142107.34        91391.77        366168.42  166187.94        1         0
5   131876.90        99814.71        362861.36  156991.12        0         1
6   134615.46       147198.87        127716.82  156122.51        0         0
7   130298.13       145530.06        323876.68  155752.60        1         0
8   120542.52       148718.95        311613.29  152211.77        0         1
9   123334.88       108679.17        304981.62  149759.96        0         0
10  101913.08       110594.11        229160.95  146121.95        1         0
11  100671.96        91790.61        249744.55  144259.40        0         0
12   93863.75       127320.38        249839.44  141585.52        1         0
13   91992.39       135495.07        252664.93  134307.35        0         0
14  119943.24       156547.42        256512.92  132602.65        1         0
15  114523.61       122616.84        261776.23  129917.04        0         1
16   78013.11       121597.55        264346.06  126992.93        0         0
17   94657.16       145077.58        282574.31  125370.37        0         1
18   91749.16       114175.79        294919.57  124266.90        1         0
19   86419.70       153514.11             0.00  122776.86        0         1
20   76253.86       113867.30        298664.47  118474.03        0         0
21   78389.47       153773.43        299737.29  111313.02        0         1
22   73994.56       122782.75        303319.26  110352.25        1         0
23   67532.53       105751.03        304768.73  108733.99        1         0
24   77044.01        99281.34        140574.81  108552.04        0         1
25   64664.71       139553.16        137962.62  107404.34        0         0
26   75328.87       144135.98        134050.07  105733.54        1         0
27   72107.60       127864.55        353183.81  105008.31        0         1
28   66051.52       182645.56        118148.20  103282.38        1         0
29   65605.48       153032.06        107138.38  101004.64        0         1
30   61994.48       115641.28         91131.24   99937.59        1         0
31   61136.38       152701.92         88218.23   97483.56        0         1
32   63408.86       129219.61         46085.25   97427.84        0         0
33   55493.95       103057.49        214634.81   96778.92        1         0
34   46426.07       157693.92        210797.67   96712.80        0         0
35   46014.02        85047.44        205517.64   96479.51        0         1
36   28663.76       127056.21        201126.82   90708.19        1         0
37   44069.95        51283.14        197029.42   89949.14        0         0
38   20229.59        65947.93        185265.10   81229.06        0         1
39   38558.51        82982.09        174999.30   81005.76        0         0
40   28754.33       118546.05        172795.67   78239.91        0         0
41   27892.92        84710.77        164470.71   77798.83        1         0
42   23640.93        96189.63        148001.11   71498.49        0         0
43   15505.73       127382.30         35534.17   69758.98        0         1
44   22177.74       154806.14         28334.72   65200.33        0         0
45    1000.23       124153.04          1903.93   64926.08        0         1
46    1315.46       115816.21        297114.46   49490.75        1         0
47       0.00       135426.92             0.00   42559.73        0         0
48     542.05        51743.15             0.00   35673.41        0         1
49       0.00       116983.80         45173.06   14681.40        0         0

In [40]:
y=data_new['Profit']
y.values

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [41]:
x=data_new.drop(['Profit'],axis=1)
x.values

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00,
        0.00

In [42]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[ 2.01641149e+00,  5.60752915e-01,  2.15394309e+00,
        -6.85994341e-01,  1.39326109e+00],
       [ 1.95586034e+00,  1.08280658e+00,  1.92360040e+00,
        -6.85994341e-01, -7.17740563e-01],
       [ 1.75436374e+00, -7.28257028e-01,  1.62652767e+00,
         1.45773797e+00, -7.17740563e-01],
       [ 1.55478369e+00, -9.63646307e-02,  1.42221024e+00,
        -6.85994341e-01,  1.39326109e+00],
       [ 1.50493720e+00, -1.07991935e+00,  1.28152771e+00,
         1.45773797e+00, -7.17740563e-01],
       [ 1.27980001e+00, -7.76239071e-01,  1.25421046e+00,
        -6.85994341e-01,  1.39326109e+00],
       [ 1.34006641e+00,  9.32147208e-01, -6.88149930e-01,
        -6.85994341e-01, -7.17740563e-01],
       [ 1.24505666e+00,  8.71980011e-01,  9.32185978e-01,
         1.45773797e+00, -7.17740563e-01],
       [ 1.03036886e+00,  9.86952101e-01,  8.30886909e-01,
        -6.85994341e-01,  1.39326109e+00],
       [ 1.09181921e+00, -4.56640246e-01,  7.76107440e-01,
        -6.85994341e-01

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=0)

In [44]:
from sklearn.ensemble import RandomForestRegressor
clf=RandomForestRegressor(n_estimators=100,random_state=0)
clf.fit(x_train,y_train)


RandomForestRegressor(n_estimators=1000, random_state=0)

In [45]:
y_pred=clf.predict(x_test)
y_pred

array([103908.6964 , 134087.88439, 137167.8401 ,  80552.56394,
       182769.01815, 119340.85904,  71671.64533,  99758.91712,
       116814.48466, 167360.80668, 101028.18457,  87924.60558,
       117150.61801,  89478.84023, 133210.49811, 153782.72614,
       147314.0186 ])

In [46]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
score

0.9268746676963855

In [47]:
from sklearn import metrics 

print("MAE:",metrics.mean_absolute_error(y_test,y_pred))
print("MsE:",metrics.mean_squared_error(y_test,y_pred))
print("RMSE:",np.sqrt(metrics.mean_absolute_error(y_test,y_pred)))


MAE: 7156.912777058991
MsE: 69381584.48382077
RMSE: 84.59853885888923
