# Random Number Generation

In [3]:
import numpy as np
np.random.randint(0,10,7)                 #start, stop, n    (o/p change wrt to every run) bcoz it is selected in random way.

array([8, 8, 4, 3, 7, 8, 2])

In [5]:
np.random.randint(4,10,(3,5))              #2d with row and column


array([[7, 9, 4, 9, 7],
       [9, 4, 5, 8, 6],
       [4, 5, 4, 6, 9]])

In [9]:
np.random.rand(6)      #only specify the n, and it takes the values b/w 0 and 1

array([0.99585017, 0.42802301, 0.65796432, 0.19037231, 0.85240669,
       0.37797316])

In [11]:
np.random.randn(6)      #specify only n, it takes the values from any range, different o/p for each run

array([ 1.3536575 ,  0.10885435, -1.58613835, -0.27204878,  0.53043875,
       -1.48112386])

In [17]:
np.random.randint(6)

4

seed()   - to give the same sequence of random numbers

In [22]:
np.random.seed(1)
np.random.randn(5)

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763])

# Min and Max

In [21]:
L=[1,2,3,4,5,6,7,8,99,45,64]
L1=np.array(L)
L1

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99, 45, 64])

In [22]:
min(L1)

1

In [23]:
max(L1)

99

# Reshape

In [23]:
ar=np.arange(42)        #()-inside how much range
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [24]:
ar.reshape(2,7,3)      #inside bracket specify the row and column.

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41]]])

# Indexing

In [32]:
L= np.arange(3,10,1)
L

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
L[3]

6

In [34]:
L[-5]

5

In [35]:
L[3:5]

array([6, 7])

In [36]:
L[:5]     # from 0 to 4

array([3, 4, 5, 6, 7])

In [37]:
L[2:]

array([5, 6, 7, 8, 9])

In [46]:
S=np.arange(1,25,3)
S

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [47]:
S[2:5]=20                   #  up to 2 to 4th element assign as 20
S

array([ 1,  4, 20, 20, 20, 16, 19, 22])

In [48]:
L=np.arange(1,25,3)        #create an array with 3 as sliced
L

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [49]:
sliced=L[2:4].copy()  # copy from 
sliced

array([ 7, 10])

In [50]:
sliced[:]=30     #: represent full value as 30
sliced

array([30, 30])

# 2-D array

In [51]:
my_list=np.array([[1,2,3],[4,5,6],[7,8,9]])
my_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
my_list[0][0]             # 0th row and 0th column

1

In [54]:
my_list[2][1]               #2nd row  1st column

8

In [55]:
my_list[0:2,0:2]       0 to 2 rows, 0 to 2 columns

array([[1, 2],
       [4, 5]])

In [7]:
my_list=np.array([[1,2,3,4],[8,4,5,6],[7,8,9,10]])
# my_list
c=my_list[1:3,1:2]
print(my_list)
print("\n",c)


[[ 1  2  3  4]
 [ 8  4  5  6]
 [ 7  8  9 10]]

 [[4]
 [8]]


In [10]:
my_list=np.array([[1,2,3,4],[8,4,5,6],[7,8,9,10]])
print(my_list)
c=my_list[:,1:]
print(c)

[[ 1  2  3  4]
 [ 8  4  5  6]
 [ 7  8  9 10]]
[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]]


In [65]:
L=np.arange(1,30,5)
L

array([ 1,  6, 11, 16, 21, 26])

In [66]:
L[L>9]

array([11, 16, 21, 26])

In [67]:
L>9

array([False, False,  True,  True,  True,  True])

# Mathematical Operation

In [4]:
L=np.arange(0,10)
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
L+3


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
L-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [72]:
L*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
L/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:

np.sqrt(L)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.cos(L)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [8]:
np.tan(L)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [9]:
np.sin(L)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [10]:
np.exp(L)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

# Statistics

In [11]:
L.max()

9

In [12]:
L.min()

0

In [13]:
L.var()            # variance

8.25

In [14]:
L.std()   #standard deviation

2.8722813232690143

In [18]:
my_2D=[[1,2,3,4],[5,2,3,4],[2,4,5,8]]
my_2D

[[1, 2, 3, 4], [5, 2, 3, 4], [2, 4, 5, 8]]

In [20]:
my_2D=np.array(my_2D)
my_2D

array([[1, 2, 3, 4],
       [5, 2, 3, 4],
       [2, 4, 5, 8]])

In [22]:
my_2D.sum(axis=0)               #column addition

array([ 8,  8, 11, 16])

In [23]:
my_2D.sum(axis=1)              #row addition

array([10, 14, 19])